tailwind.config = {
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-tertiary': '#ffffff',
        'on-tertiary-fixed-variant': '#005145',
        'tertiary-container': '#00473c',
        surface: '#faf8ff',
        'surface-container-high': '#e2e7ff',
        'on-tertiary-container': '#00bfa5',
        tertiary: '#002f27',
        'outline-variant': '#c4c6d2',
        'surface-variant': '#dae2fd',
        'on-secondary-container': '#006f63',
        'surface-container-low': '#f2f3ff',
        'on-secondary-fixed-variant': '#005047',
        'on-secondary': '#ffffff',
        background: '#faf8ff',
        primary: '#00265d',
        secondary: '#006b5f',
        'tertiary-fixed-dim': '#44ddc1',
        'surface-dim': '#d2d9f4',
        'secondary-fixed': '#79f7e3',
        'tertiary-fixed': '#68fadd',
        'error-container': '#ffdad6',
        'on-primary-fixed-variant': '#1b448b',
        'surface-container-highest': '#dae2fd',
        'inverse-on-surface': '#eef0ff',
        'primary-container': '#0d3b82',
        error: '#ba1a1a',
        'on-primary-fixed': '#001944',
        'surface-container-lowest': '#ffffff',
        'on-tertiary-fixed': '#00201a',
        'inverse-primary': '#afc6ff',
        'surface-container': '#eaedff',
        'secondary-fixed-dim': '#59dbc7',
        outline: '#747782',
        'on-primary-container': '#86a8f6',
        'on-surface': '#131b2e',
        'secondary-container': '#76f4e0',
        'on-error-container': '#93000a',
        'on-background': '#131b2e',
        'on-secondary-fixed': '#00201c',
        'surface-tint': '#385ca5',
        'on-error': '#ffffff',
        'inverse-surface': '#283044',
        'on-surface-variant': '#434751',
        'primary-fixed-dim': '#afc6ff',
        'primary-fixed': '#d9e2ff',
        'on-primary': '#ffffff',
        'surface-bright': '#faf8ff',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'space-xs': '0.25rem',
        'space-md': '1rem',
        'margin-mobile': '1.25rem',
        gutter: '1.5rem',
        'space-sm': '0.5rem',
        'space-lg': '1.5rem',
        margin: '2rem',
        'gutter-mobile': '1rem',
        'space-xl': '2.5rem',
      },
      fontFamily: {
        'headline-xl-mobile': [
          'Manrope',
          'system-ui',
          '-apple-system',
          'sans-serif',
        ],
        'headline-md': ['Manrope', 'system-ui', '-apple-system', 'sans-serif'],
        'body-md': ['Manrope', 'system-ui', '-apple-system', 'sans-serif'],
        'label-caps': ['Manrope', 'system-ui', '-apple-system', 'sans-serif'],
        'headline-lg-mobile': [
          'Manrope',
          'system-ui',
          '-apple-system',
          'sans-serif',
        ],
        'headline-xl': ['Manrope', 'system-ui', '-apple-system', 'sans-serif'],
        'headline-sm': ['Manrope', 'system-ui', '-apple-system', 'sans-serif'],
        'headline-lg': ['Manrope', 'system-ui', '-apple-system', 'sans-serif'],
        'body-lg': ['Manrope', 'system-ui', '-apple-system', 'sans-serif'],
        'label-mono-sm': ['JetBrains Mono', 'ui-monospace', 'monospace'],
        'body-sm': ['Manrope', 'system-ui', '-apple-system', 'sans-serif'],
      },
      fontSize: {
        'headline-xl-mobile': [
          '36px',
          { lineHeight: '44px', letterSpacing: '-0.025em', fontWeight: '800' },
        ],
        'headline-md': [
          '28px',
          { lineHeight: '36px', letterSpacing: '-0.01em', fontWeight: '600' },
        ],
        'body-md': ['15px', { lineHeight: '24px', fontWeight: '400' }],
        'label-caps': [
          '11px',
          { lineHeight: '16px', letterSpacing: '0.08em', fontWeight: '700' },
        ],
        'headline-lg-mobile': [
          '28px',
          { lineHeight: '36px', letterSpacing: '-0.015em', fontWeight: '700' },
        ],
        'headline-xl': [
          '56px',
          { lineHeight: '64px', letterSpacing: '-0.03em', fontWeight: '800' },
        ],
        'headline-sm': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'headline-lg': [
          '40px',
          { lineHeight: '48px', letterSpacing: '-0.02em', fontWeight: '700' },
        ],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'label-mono-sm': [
          '12px',
          { lineHeight: '16px', letterSpacing: '0.02em', fontWeight: '500' },
        ],
        'body-sm': ['13px', { lineHeight: '20px', fontWeight: '400' }],
      },
    },
  },
};
